[build]
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "nft"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Production environment variables (set these in Netlify dashboard)
# STRIPE_SECRET_KEY = "your_stripe_secret_key_here"
# STRIPE_PUBLISHABLE_KEY = "your_stripe_publishable_key_here" 